# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: network.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import network_pb2


class BotNodeBase(abc.ABC):

    @abc.abstractmethod
    async def GetInfo(self, stream):
        pass

    @abc.abstractmethod
    async def Register(self, stream):
        pass

    @abc.abstractmethod
    async def SendMessage(self, stream):
        pass

    @abc.abstractmethod
    async def GetMessages(self, stream):
        pass

    @abc.abstractmethod
    async def IsOnline(self, stream):
        pass

    def __mapping__(self):
        return {
            '/network.BotNode/GetInfo': grpclib.const.Handler(
                self.GetInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                network_pb2.Empty,
                network_pb2.ServerInfo,
            ),
            '/network.BotNode/Register': grpclib.const.Handler(
                self.Register,
                grpclib.const.Cardinality.UNARY_UNARY,
                network_pb2.User,
                network_pb2.Status,
            ),
            '/network.BotNode/SendMessage': grpclib.const.Handler(
                self.SendMessage,
                grpclib.const.Cardinality.UNARY_UNARY,
                network_pb2.MessageRequest,
                network_pb2.Empty,
            ),
            '/network.BotNode/GetMessages': grpclib.const.Handler(
                self.GetMessages,
                grpclib.const.Cardinality.UNARY_STREAM,
                network_pb2.GetMessagesRequest,
                network_pb2.Message,
            ),
            '/network.BotNode/IsOnline': grpclib.const.Handler(
                self.IsOnline,
                grpclib.const.Cardinality.UNARY_UNARY,
                network_pb2.User,
                network_pb2.Status,
            ),
        }


class BotNodeStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/network.BotNode/GetInfo',
            network_pb2.Empty,
            network_pb2.ServerInfo,
        )
        self.Register = grpclib.client.UnaryUnaryMethod(
            channel,
            '/network.BotNode/Register',
            network_pb2.User,
            network_pb2.Status,
        )
        self.SendMessage = grpclib.client.UnaryUnaryMethod(
            channel,
            '/network.BotNode/SendMessage',
            network_pb2.MessageRequest,
            network_pb2.Empty,
        )
        self.GetMessages = grpclib.client.UnaryStreamMethod(
            channel,
            '/network.BotNode/GetMessages',
            network_pb2.GetMessagesRequest,
            network_pb2.Message,
        )
        self.IsOnline = grpclib.client.UnaryUnaryMethod(
            channel,
            '/network.BotNode/IsOnline',
            network_pb2.User,
            network_pb2.Status,
        )
